FROM ubuntu
MAINTAINER Borlay Dániel <borlay.daniel@gmail.com>

COPY auth.sh /usr/sbin/auth.sh
COPY auth-service.py /usr/sbin/auth-service.py

RUN apt-get -y update
RUN apt-get -y install vim bash python-oauth python-mysqldb python \
    python-flask
RUN chmod +x /usr/sbin/auth.sh
RUN chmod +x /usr/sbin/auth-service.py

EXPOSE 8081
