FROM centos
MAINTAINER Borlay Dániel <borlay.daniel@gmail.com>

COPY reserve.sh /usr/sbin/reserve.sh
COPY consul /usr/bin/consul
RUN mkdir -p /etc/consul.d
COPY reserve.json /etc/consul.d/reserve.json

RUN yum -y update
RUN yum -y install vim java-1.8.0-openjdk-devel tomcat
RUN chmod +x /usr/sbin/reserve.sh
RUN chmod +x /usr/bin/consul

EXPOSE 8888
