FROM centos
MAINTAINER Borlay Dániel <borlay.daniel@gmail.com>

COPY order.sh /usr/sbin/order.sh
COPY consul /usr/bin/consul
RUN mkdir -p /etc/consul.d
COPY order.json /etc/consul.d/order.json
RUN mkdir -p /order
COPY . /order/java

RUN yum -y update
RUN yum -y install vim java-1.8.0-openjdk-devel tomcat maven
RUN chmod +x /usr/sbin/order.sh
RUN chmod +x /usr/bin/consul

EXPOSE 8888
