FROM haproxy
MAINTAINER Borlay Dániel <borlay.daniel@gmail.com>

COPY proxy.sh /usr/sbin/proxy.sh

RUN apt-get -y update
RUN apt-get -y install vim
RUN chmod +x /usr/sbin/proxy.sh

ENTRYPOINT proxy.sh

EXPOSE 8080
