FROM httpd
MAINTAINER Borlay Dániel <borlay.daniel@gmail.com>

COPY webserver.sh /usr/sbin/webserver.sh
COPY index.html /var/www/html/index.html
COPY login.php /var/www/html/login.php
COPY store.php /var/www/html/store.php

RUN apt-get -y update
RUN apt-get -y install vim php5 php5-mysql
RUN chmod +x /usr/sbin/webserver.sh

EXPOSE 80 443
